# Load env
. ~/.env

# Load aliases
. ~/.aliasrc

# {{{ ZSH settings
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
setopt PROMPT_SUBST
setopt HIST_IGNORE_SPACE
unsetopt beep
unsetopt PROMPT_CR
autoload -Uz compinit
autoload -U colors && colors
zstyle :compinstall filename '/home/$USER/.zshrc'
compinit
bindkey -e
bindkey "^[[3~" delete-char
bindkey "^H"    backward-delete-word
bindkey "^[[7~" beginning-of-line
bindkey "^[Oc"  forward-word
bindkey "^[Od"  backward-word
bindkey "^[[A"  history-search-backward
bindkey "^[[B"  history-search-forward
# }}}

# {{{ Local
. ~/.zshrc.local
# }}}

# {{{ Welcome prompt if not in TMUX
if ! { [ -n "$TMUX" ]; } then
  shellfection-welcome
fi
# }}}
